### ISSUE TITLE
Still have counting issues

### ISSUE THREAD

**Issue by dudeofawesome** [Virginity-Bot/VirginityBot-legacy#2]
haven't tested this yet, but I think that we might have an issue comparing unaccounted hours in UTC vs local time.

**Comment by dudeofawesome** [comment]
First and last `/leaderboard`s were taken while in VC, middle was taken while out of VC.

![image](https://user-images.githubusercontent.com/1683595/77602265-37fd0780-6eca-11ea-80fd-c422036daf9a.png)

**Comment by BriianPowell** [comment]
I believe this is resolved with latest merge
